#!/usr/bin/env python3
import json
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LEGACY_TEXTURES = ROOT / "src/main/resources/assets/got/textures/items"
TEXTURES = ROOT / "src/main/resources/assets/got/textures/item"
MODELS = ROOT / "src/main/resources/assets/got/models/item/held"
MANIFEST = ROOT / "src/main/resources/assets/got/held_weapon_models.txt"


def write_model(path, texture):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps({
        "parent": "minecraft:item/handheld",
        "textures": {"layer0": texture},
    }, indent=2) + "\n", encoding="utf-8")


specs = []
for folder, scale in (("large-2x", 2), ("large-3x", 3)):
    source_dir = LEGACY_TEXTURES / folder
    target_dir = TEXTURES / folder
    target_dir.mkdir(parents=True, exist_ok=True)
    for source in sorted(source_dir.glob("*.png")):
        texture = target_dir / source.name
        shutil.copyfile(source, texture)
        item_id = texture.stem
        if item_id.lower() != item_id:
            raise AssertionError(f"modern resource path is not lowercase: {texture}")
        model_id = f"got:item/held/{item_id}"
        write_model(MODELS / f"{item_id}.json", f"got:item/{folder}/{item_id}")
        specs.append((f"got:{item_id}", model_id, scale))

# The five vlarge textures use legacy camel-case filenames. Preserve those
# originals and create lowercase aliases in the same source folder so modern
# ResourceLocation validation can load them for vanilla sword hand models.
vanilla = {
    "swordWood": "wooden_sword",
    "swordStone": "stone_sword",
    "swordIron": "iron_sword",
    "swordGold": "golden_sword",
    "swordDiamond": "diamond_sword",
}
for legacy_name, item_id in vanilla.items():
    (TEXTURES / "vlarge-2x").mkdir(parents=True, exist_ok=True)
    source = LEGACY_TEXTURES / "vlarge-2x" / f"{legacy_name}.png"
    alias_name = legacy_name.lower()
    alias = TEXTURES / "vlarge-2x" / f"{alias_name}.png"
    shutil.copyfile(source, alias)
    model_id = f"got:item/held/vanilla/{item_id}"
    write_model(MODELS / "vanilla" / f"{item_id}.json",
                f"got:item/vlarge-2x/{alias_name}")
    specs.append((f"minecraft:{item_id}", model_id, 2))

specs.sort()
lines = [
    "# inventory item|hand-only baked model|legacy canvas scale",
    "# generated by migration/generate-held-weapon-models.py",
]
lines.extend(f"{item}|{model}|{scale}" for item, model, scale in specs)
MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"generated {len(specs)} hand-only weapon models")
