package got.wildlife;
import net.minecraft.nbt.CompoundTag; import net.minecraft.server.level.ServerLevel; import net.minecraft.world.damagesource.DamageSource; import net.minecraft.world.entity.*; import net.minecraft.world.entity.ai.goal.*; import net.minecraft.world.entity.ai.goal.target.HurtByTargetGoal; import net.minecraft.world.entity.animal.Animal; import net.minecraft.world.entity.player.Player; import net.minecraft.world.item.ItemStack; import net.minecraft.world.item.Items; import net.minecraft.world.item.crafting.Ingredient; import net.minecraft.world.level.Level; import org.jetbrains.annotations.Nullable; import java.util.List;
public abstract class GOTDefensiveAnimalEntity extends Animal {
 private int angryTicks; protected GOTDefensiveAnimalEntity(EntityType<? extends Animal> t,Level l){super(t,l);}
 protected Ingredient food(){return Ingredient.of(Items.WHEAT);}
 @Override protected void registerGoals(){goalSelector.addGoal(0,new FloatGoal(this));goalSelector.addGoal(1,new MeleeAttackGoal(this,1.35,true));goalSelector.addGoal(2,new PanicGoal(this,1.35));goalSelector.addGoal(3,new BreedGoal(this,1));goalSelector.addGoal(4,new TemptGoal(this,1.1,food(),false));goalSelector.addGoal(5,new FollowParentGoal(this,1.1));goalSelector.addGoal(6,new WaterAvoidingRandomStrollGoal(this,1));goalSelector.addGoal(7,new LookAtPlayerGoal(this,Player.class,8));goalSelector.addGoal(8,new RandomLookAroundGoal(this));targetSelector.addGoal(1,new HurtByTargetGoal(this));}
 @Override public boolean hurt(DamageSource s,float a){boolean h=super.hurt(s,a);Entity x=s.getEntity();if(h&&x instanceof LivingEntity l){if(isBaby()){List<? extends GOTDefensiveAnimalEntity> adults=level().getEntitiesOfClass(getClass(),getBoundingBox().inflate(12),e->!e.isBaby());adults.forEach(e->e.anger(l));}else anger(l);}return h;}
 protected final void anger(LivingEntity l){setTarget(l);angryTicks=200;}
 @Override public void aiStep(){super.aiStep();if(!level().isClientSide&&angryTicks>0&&--angryTicks==0)setTarget(null);}
 @Override public boolean isFood(ItemStack s){return food().test(s);} @Nullable @Override public Animal getBreedOffspring(ServerLevel l,AgeableMob m){return (Animal)getType().create(l);}
 @Override public void addAdditionalSaveData(CompoundTag t){super.addAdditionalSaveData(t);t.putInt("GOTAngryTicks",angryTicks);} @Override public void readAdditionalSaveData(CompoundTag t){super.readAdditionalSaveData(t);angryTicks=t.getInt("GOTAngryTicks");}
}