package got.world.flora;

import got.GOTBlocks;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;

import java.util.function.Supplier;

/**
 * Runtime tree palette reconstructed from the legacy GOTTreeType catalogue.
 * Each species keeps its own wood and leaves; shapes are generated by
 * {@link GOTTreeGenerator} for both chunk decoration and sapling growth.
 */
public enum GOTTreeSpecies {
    CATALPA("catalpa", () -> GOTBlocks.CATALPA_LOG.get(), () -> GOTBlocks.CATALPA_LEAVES.get(), Shape.DECIDUOUS, 6, 10),
    IBBINIA("ibbinia", () -> GOTBlocks.IBBINIA_LOG.get(), () -> GOTBlocks.IBBINIA_LEAVES.get(), Shape.CONIFER, 10, 18),
    ULTHOS("ulthos", () -> GOTBlocks.ULTHOS_LOG.get(), () -> GOTBlocks.ULTHOS_LEAVES.get(), Shape.GIANT, 12, 19),
    ULTHOS_RED("ulthos_red", () -> GOTBlocks.ULTHOS_RED_LOG.get(), () -> GOTBlocks.ULTHOS_RED_LEAVES.get(), Shape.GIANT, 12, 20),
    ARAMANT("aramant", () -> GOTBlocks.ARAMANT_LOG.get(), () -> GOTBlocks.ARAMANT_LEAVES.get(), Shape.DECIDUOUS, 5, 9),
    BANANA("banana", () -> GOTBlocks.BANANA_LOG.get(), () -> GOTBlocks.BANANA_LEAVES.get(), Shape.PALM, 5, 8),
    BEECH("beech", () -> GOTBlocks.BEECH_LOG.get(), () -> GOTBlocks.BEECH_LEAVES.get(), Shape.DECIDUOUS, 6, 11),
    HOLLY("holly", () -> GOTBlocks.HOLLY_LOG.get(), () -> GOTBlocks.HOLLY_LEAVES.get(), Shape.DECIDUOUS, 5, 9),
    DATE_PALM("date_palm", () -> GOTBlocks.DATE_PALM_LOG.get(), () -> GOTBlocks.DATE_PALM_LEAVES.get(), Shape.PALM, 6, 10),
    LARCH("larch", () -> GOTBlocks.LARCH_LOG.get(), () -> GOTBlocks.LARCH_LEAVES.get(), Shape.CONIFER, 8, 15),
    MANGROVE("mangrove", () -> GOTBlocks.MANGROVE_LOG.get(), () -> GOTBlocks.MANGROVE_LEAVES.get(), Shape.MANGROVE, 5, 8),
    MAPLE("maple", () -> GOTBlocks.MAPLE_LOG.get(), () -> GOTBlocks.MAPLE_LEAVES.get(), Shape.DECIDUOUS, 5, 10),
    BAOBAB("baobab", () -> GOTBlocks.BAOBAB_LOG.get(), () -> GOTBlocks.BAOBAB_LEAVES.get(), Shape.BAOBAB, 8, 13),
    CEDAR("cedar", () -> GOTBlocks.CEDAR_LOG.get(), () -> GOTBlocks.CEDAR_LEAVES.get(), Shape.CONIFER, 9, 17),
    CHESTNUT("chestnut", () -> GOTBlocks.CHESTNUT_LOG.get(), () -> GOTBlocks.CHESTNUT_LEAVES.get(), Shape.DECIDUOUS, 6, 11),
    FIR("fir", () -> GOTBlocks.FIR_LOG.get(), () -> GOTBlocks.FIR_LEAVES.get(), Shape.CONIFER, 8, 16),
    LEMON("lemon", () -> GOTBlocks.LEMON_LOG.get(), () -> GOTBlocks.LEMON_LEAVES.get(), Shape.DECIDUOUS, 5, 9),
    LIME("lime", () -> GOTBlocks.LIME_LOG.get(), () -> GOTBlocks.LIME_LEAVES.get(), Shape.DECIDUOUS, 5, 9),
    ORANGE("orange", () -> GOTBlocks.ORANGE_LOG.get(), () -> GOTBlocks.ORANGE_LEAVES.get(), Shape.DECIDUOUS, 5, 9),
    PINE("pine", () -> GOTBlocks.PINE_LOG.get(), () -> GOTBlocks.PINE_LEAVES.get(), Shape.CONIFER, 9, 17),
    CYPRESS("cypress", () -> GOTBlocks.CYPRESS_LOG.get(), () -> GOTBlocks.CYPRESS_LEAVES.get(), Shape.CYPRESS, 9, 17),
    MAHOGANY("mahogany", () -> GOTBlocks.MAHOGANY_LOG.get(), () -> GOTBlocks.MAHOGANY_LEAVES.get(), Shape.TROPICAL, 9, 16),
    OLIVE("olive", () -> GOTBlocks.OLIVE_LOG.get(), () -> GOTBlocks.OLIVE_LEAVES.get(), Shape.SAVANNA, 5, 9),
    WILLOW("willow", () -> GOTBlocks.WILLOW_LOG.get(), () -> GOTBlocks.WILLOW_LEAVES.get(), Shape.WILLOW, 6, 10),
    ALMOND("almond", () -> GOTBlocks.ALMOND_LOG.get(), () -> GOTBlocks.ALMOND_LEAVES.get(), Shape.DECIDUOUS, 5, 9),
    ASPEN("aspen", () -> GOTBlocks.ASPEN_LOG.get(), () -> GOTBlocks.ASPEN_LEAVES.get(), Shape.DECIDUOUS, 8, 16),
    FOTINIA("fotinia", () -> GOTBlocks.FOTINIA_LOG.get(), () -> GOTBlocks.FOTINIA_LEAVES.get(), Shape.DECIDUOUS, 5, 9),
    GREEN_OAK("green_oak", () -> GOTBlocks.GREEN_OAK_LOG.get(), () -> GOTBlocks.GREEN_OAK_LEAVES.get(), Shape.GIANT, 9, 16),
    PALM("palm", () -> GOTBlocks.PALM_LOG.get(), () -> GOTBlocks.PALM_LEAVES.get(), Shape.PALM, 7, 12),
    PLUM("plum", () -> GOTBlocks.PLUM_LOG.get(), () -> GOTBlocks.PLUM_LEAVES.get(), Shape.DECIDUOUS, 5, 8),
    POMEGRANATE("pomegranate", () -> GOTBlocks.POMEGRANATE_LOG.get(), () -> GOTBlocks.POMEGRANATE_LEAVES.get(), Shape.SAVANNA, 5, 9),
    REDWOOD("redwood", () -> GOTBlocks.REDWOOD_LOG.get(), () -> GOTBlocks.REDWOOD_LEAVES.get(), Shape.REDWOOD, 18, 30),
    DRAGON("dragon", () -> GOTBlocks.DRAGON_LOG.get(), () -> GOTBlocks.DRAGON_LEAVES.get(), Shape.SAVANNA, 6, 11),
    KANUKA("kanuka", () -> GOTBlocks.KANUKA_LOG.get(), () -> GOTBlocks.KANUKA_LEAVES.get(), Shape.SAVANNA, 5, 9),
    OAK("oak", () -> GOTBlocks.OAK_LOG.get(), () -> GOTBlocks.OAK_LEAVES.get(), Shape.DECIDUOUS, 5, 10),
    WEIRWOOD("weirwood", () -> GOTBlocks.WEIRWOOD_LOG.get(), () -> GOTBlocks.WEIRWOOD_LEAVES.get(), Shape.GIANT, 11, 18),

    VANILLA_BIRCH("birch", () -> Blocks.BIRCH_LOG, () -> Blocks.BIRCH_LEAVES, Shape.DECIDUOUS, 7, 13),
    VANILLA_SPRUCE("spruce", () -> Blocks.SPRUCE_LOG, () -> Blocks.SPRUCE_LEAVES, Shape.CONIFER, 8, 17),
    VANILLA_ACACIA("acacia", () -> Blocks.ACACIA_LOG, () -> Blocks.ACACIA_LEAVES, Shape.SAVANNA, 5, 9),
    VANILLA_JUNGLE("jungle", () -> Blocks.JUNGLE_LOG, () -> Blocks.JUNGLE_LEAVES, Shape.TROPICAL, 9, 17),
    VANILLA_DARK_OAK("dark_oak", () -> Blocks.DARK_OAK_LOG, () -> Blocks.DARK_OAK_LEAVES, Shape.GIANT, 7, 13),
    DEAD_OAK("oak", () -> GOTBlocks.OAK_LOG.get(), () -> Blocks.AIR, Shape.DEAD, 5, 10),
    CHARRED("charred", () -> Blocks.BASALT, () -> Blocks.AIR, Shape.DEAD, 5, 11);

    public enum Shape {
        DECIDUOUS, CONIFER, CYPRESS, SAVANNA, PALM, WILLOW, MANGROVE,
        TROPICAL, GIANT, REDWOOD, BAOBAB, DEAD
    }

    private final String id;
    private final Supplier<Block> log;
    private final Supplier<Block> leaves;
    private final Shape shape;
    private final int minimumHeight;
    private final int maximumHeight;

    GOTTreeSpecies(String id, Supplier<Block> log, Supplier<Block> leaves, Shape shape,
                   int minimumHeight, int maximumHeight) {
        this.id = id;
        this.log = log;
        this.leaves = leaves;
        this.shape = shape;
        this.minimumHeight = minimumHeight;
        this.maximumHeight = maximumHeight;
    }

    public String id() {
        return id;
    }

    public Block log() {
        return log.get();
    }

    public Block leaves() {
        return leaves.get();
    }

    public Shape shape() {
        return shape;
    }

    public int randomHeight(net.minecraft.util.RandomSource random) {
        return minimumHeight + random.nextInt(maximumHeight - minimumHeight + 1);
    }

    public boolean hasLeaves() {
        return leaves() != Blocks.AIR;
    }

    public String fallenLeavesId() {
        return id + "_fallen_leaves";
    }
}
