package got;

import got.faction.GOTFaction;
import net.minecraft.resources.ResourceLocation;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * The complete legacy heraldry catalogue. IDs and ordering match the original
 * GPL-licensed 1.7.10 mod so commands, structures, and future NPC data can use
 * the same stable values without registering 605 separate items.
 */
public record GOTBannerType(int legacyId, String name, String factionCode) {
    private static final List<GOTBannerType> VALUES = createTypes();
    private static final Map<Integer, GOTBannerType> BY_ID = indexById();
    private static final Map<String, GOTBannerType> BY_NAME = indexByName();

    public static final GOTBannerType DEFAULT = byLegacyId(0);
    public static final GOTBannerType NULL = byName("null");

    public GOTBannerType {
        if (legacyId < 0 || name.isBlank() || factionCode.isBlank()) {
            throw new IllegalArgumentException("Invalid banner catalogue row");
        }
    }

    public static List<GOTBannerType> values() {
        return VALUES;
    }

    public static GOTBannerType byLegacyId(int legacyId) {
        GOTBannerType type = BY_ID.get(legacyId);
        if (type != null) return type;
        GOTBannerType fallback = BY_NAME.get("null");
        return fallback != null ? fallback : VALUES.get(0);
    }

    public static GOTBannerType byName(String name) {
        if (name == null) return byLegacyId(-1);
        GOTBannerType type = BY_NAME.get(name);
        return type != null ? type : byLegacyId(-1);
    }

    public String translationKey() {
        return "item.got:banner." + name + ".name";
    }

    public ResourceLocation texture() {
        return ResourceLocation.fromNamespaceAndPath(
                GOTMod.MOD_ID, "textures/entity/banner/" + name.toLowerCase(Locale.ROOT) + ".png");
    }

    public GOTFaction faction() {
        return GOTFaction.byId(factionCode).orElse(GOTFaction.UNALIGNED);
    }

    private static List<GOTBannerType> createTypes() {
        ArrayList<GOTBannerType> types = new ArrayList<>(605);
        add(types, 613, "walker", "WHITE_WALKER");
        add(types, 495, "wildling", "WILDLING");
        add(types, 496, "thenn", "WILDLING");
        add(types, 497, "redbeard", "WILDLING");
        add(types, 499, "night", "NIGHT_WATCH");
        add(types, 1, "robb", "NORTH");
        add(types, 0, "eddard", "NORTH");
        add(types, 2, "robbBook", "NORTH");
        add(types, 3, "umber", "NORTH");
        add(types, 4, "umberBook", "NORTH");
        add(types, 5, "bolton", "NORTH");
        add(types, 6, "boltonbook", "NORTH");
        add(types, 7, "dustin", "NORTH");
        add(types, 8, "barbrey", "NORTH");
        add(types, 9, "karstark", "NORTH");
        add(types, 10, "karstarkBook", "NORTH");
        add(types, 11, "locke", "NORTH");
        add(types, 12, "manderly", "NORTH");
        add(types, 13, "manderlyBook", "NORTH");
        add(types, 14, "mormont", "NORTH");
        add(types, 15, "mormontBook", "NORTH");
        add(types, 16, "reed", "NORTH");
        add(types, 17, "reedBook", "NORTH");
        add(types, 18, "reedHBO", "NORTH");
        add(types, 19, "ryswell", "NORTH");
        add(types, 20, "rodrikryswell", "NORTH");
        add(types, 21, "cerwyn", "NORTH");
        add(types, 22, "whitehill", "NORTH");
        add(types, 23, "whitehillBook", "NORTH");
        add(types, 24, "flintWW", "NORTH");
        add(types, 25, "flintFF", "NORTH");
        add(types, 26, "hornwood", "NORTH");
        add(types, 27, "hornwoodBook", "NORTH");
        add(types, 28, "glover", "NORTH");
        add(types, 29, "tallhart", "NORTH");
        add(types, 30, "woolfield", "NORTH");
        add(types, 31, "glenmore", "NORTH");
        add(types, 32, "dormund", "NORTH");
        add(types, 33, "cassel", "NORTH");
        add(types, 34, "condon", "NORTH");
        add(types, 35, "marsh", "NORTH");
        add(types, 36, "mazin", "NORTH");
        add(types, 37, "mollen", "NORTH");
        add(types, 38, "poole", "NORTH");
        add(types, 39, "stout", "NORTH");
        add(types, 40, "slate", "NORTH");
        add(types, 41, "wells", "NORTH");
        add(types, 42, "fenn", "NORTH");
        add(types, 43, "burley", "NORTH");
        add(types, 44, "wull", "NORTH");
        add(types, 45, "liddle", "NORTH");
        add(types, 46, "norrey", "NORTH");
        add(types, 47, "knott", "NORTH");
        add(types, 48, "firstFlint", "NORTH");
        add(types, 49, "harclay", "NORTH");
        add(types, 50, "forrester", "NORTH");
        add(types, 51, "forresterBook", "NORTH");
        add(types, 52, "crowl", "NORTH");
        add(types, 53, "magnar", "NORTH");
        add(types, 54, "stane", "NORTH");
        add(types, 55, "ashwood", "NORTH");
        add(types, 56, "bole", "NORTH");
        add(types, 57, "branch", "NORTH");
        add(types, 58, "branfield", "NORTH");
        add(types, 59, "degore", "NORTH");
        add(types, 60, "ironsmith", "NORTH");
        add(types, 61, "lake", "NORTH");
        add(types, 62, "lightfoot", "NORTH");
        add(types, 63, "moss", "NORTH");
        add(types, 64, "ryder", "NORTH");
        add(types, 65, "towersN", "NORTH");
        add(types, 66, "waterman", "NORTH");
        add(types, 67, "woods", "NORTH");
        add(types, 68, "jonsnow", "NORTH");
        add(types, 69, "jonking", "NORTH");
        add(types, 70, "starkD", "NORTH");
        add(types, 550, "greystark", "NORTH");
        add(types, 551, "fisherSS", "NORTH");
        add(types, 552, "flintBH", "NORTH");
        add(types, 553, "frost", "NORTH");
        add(types, 554, "woodfoot", "NORTH");
        add(types, 555, "firstmen", "NORTH");
        add(types, 600, "laughingTree", "NORTH");
        add(types, 157, "greyjoy", "IRONBORN");
        add(types, 158, "greyjoyBook", "IRONBORN");
        add(types, 159, "euron", "IRONBORN");
        add(types, 160, "euronBook", "IRONBORN");
        add(types, 161, "victarion", "IRONBORN");
        add(types, 162, "blacktyde", "IRONBORN");
        add(types, 163, "botley", "IRONBORN");
        add(types, 164, "wynch", "IRONBORN");
        add(types, 165, "volmark", "IRONBORN");
        add(types, 166, "goodbrother", "IRONBORN");
        add(types, 167, "goodbrotherCL", "IRONBORN");
        add(types, 168, "goodbrotherCSK", "IRONBORN");
        add(types, 169, "goodbrotherD", "IRONBORN");
        add(types, 170, "goodbrotherO", "IRONBORN");
        add(types, 171, "goodbrotherS", "IRONBORN");
        add(types, 172, "drumm", "IRONBORN");
        add(types, 173, "merlyn", "IRONBORN");
        add(types, 174, "orkwood", "IRONBORN");
        add(types, 175, "saltcliffe", "IRONBORN");
        add(types, 176, "sunderly", "IRONBORN");
        add(types, 177, "tawney", "IRONBORN");
        add(types, 178, "farwynd", "IRONBORN");
        add(types, 179, "farwyndLL", "IRONBORN");
        add(types, 180, "harlaw", "IRONBORN");
        add(types, 181, "kenningH", "IRONBORN");
        add(types, 182, "codd", "IRONBORN");
        add(types, 183, "myre", "IRONBORN");
        add(types, 184, "ironmaker", "IRONBORN");
        add(types, 185, "sparr", "IRONBORN");
        add(types, 186, "stonetree", "IRONBORN");
        add(types, 187, "stonehouse", "IRONBORN");
        add(types, 188, "harlawTG", "IRONBORN");
        add(types, 189, "harlawHH", "IRONBORN");
        add(types, 190, "harlawGG", "IRONBORN");
        add(types, 191, "harlawHall", "IRONBORN");
        add(types, 192, "gormondgoodbrother", "IRONBORN");
        add(types, 193, "grangoodbrother", "IRONBORN");
        add(types, 569, "greyiron", "IRONBORN");
        add(types, 570, "hoare", "IRONBORN");
        add(types, 571, "dalton", "IRONBORN");
        add(types, 194, "lannister", "WESTERLANDS");
        add(types, 210, "prester", "WESTERLANDS");
        add(types, 195, "lannisterB", "WESTERLANDS");
        add(types, 196, "lannisterC", "WESTERLANDS");
        add(types, 197, "lannisterBook", "WESTERLANDS");
        add(types, 198, "banefort", "WESTERLANDS");
        add(types, 199, "banefortBook", "WESTERLANDS");
        add(types, 200, "brax", "WESTERLANDS");
        add(types, 201, "westerling", "WESTERLANDS");
        add(types, 202, "jast", "WESTERLANDS");
        add(types, 203, "kenningK", "WESTERLANDS");
        add(types, 204, "crakehall", "WESTERLANDS");
        add(types, 205, "lefford", "WESTERLANDS");
        add(types, 206, "lydden", "WESTERLANDS");
        add(types, 207, "marbrand", "WESTERLANDS");
        add(types, 208, "moreland", "WESTERLANDS");
        add(types, 209, "plumm", "WESTERLANDS");
        add(types, 211, "sarwyck", "WESTERLANDS");
        add(types, 212, "serrett", "WESTERLANDS");
        add(types, 213, "serrettBook", "WESTERLANDS");
        add(types, 214, "stackspear", "WESTERLANDS");
        add(types, 215, "farman", "WESTERLANDS");
        add(types, 216, "falwell", "WESTERLANDS");
        add(types, 217, "estren", "WESTERLANDS");
        add(types, 218, "westford", "WESTERLANDS");
        add(types, 219, "vikary", "WESTERLANDS");
        add(types, 220, "greenfield", "WESTERLANDS");
        add(types, 221, "yew", "WESTERLANDS");
        add(types, 222, "clegane", "WESTERLANDS");
        add(types, 223, "lorch", "WESTERLANDS");
        add(types, 224, "ruttiger", "WESTERLANDS");
        add(types, 225, "swyft", "WESTERLANDS");
        add(types, 226, "hetherspoon", "WESTERLANDS");
        add(types, 227, "bettley", "WESTERLANDS");
        add(types, 228, "broom", "WESTERLANDS");
        add(types, 229, "lannisport", "WESTERLANDS");
        add(types, 230, "lannisterD", "WESTERLANDS");
        add(types, 231, "lannisterTygett", "WESTERLANDS");
        add(types, 232, "payne", "WESTERLANDS");
        add(types, 233, "sarsfield", "WESTERLANDS");
        add(types, 234, "turnberry", "WESTERLANDS");
        add(types, 235, "foote", "WESTERLANDS");
        add(types, 236, "yarwyck", "WESTERLANDS");
        add(types, 237, "spicer", "WESTERLANDS");
        add(types, 238, "algood", "WESTERLANDS");
        add(types, 239, "clifton", "WESTERLANDS");
        add(types, 240, "doggett", "WESTERLANDS");
        add(types, 241, "drox", "WESTERLANDS");
        add(types, 242, "ferren", "WESTERLANDS");
        add(types, 243, "freyriverrun", "WESTERLANDS");
        add(types, 245, "hawthorne", "WESTERLANDS");
        add(types, 246, "kyndall", "WESTERLANDS");
        add(types, 247, "lannett", "WESTERLANDS");
        add(types, 248, "lanny", "WESTERLANDS");
        add(types, 249, "lantell", "WESTERLANDS");
        add(types, 250, "myatt", "WESTERLANDS");
        add(types, 251, "peckledon", "WESTERLANDS");
        add(types, 252, "tyrion", "WESTERLANDS");
        add(types, 253, "amorylorch", "WESTERLANDS");
        add(types, 572, "casterly", "WESTERLANDS");
        add(types, 573, "parren", "WESTERLANDS");
        add(types, 574, "reyne", "WESTERLANDS");
        add(types, 575, "reyneBook", "WESTERLANDS");
        add(types, 576, "tarbeck", "WESTERLANDS");
        add(types, 577, "tybolt", "WESTERLANDS");
        add(types, 71, "tully", "RIVERLANDS");
        add(types, 72, "tullyBook", "RIVERLANDS");
        add(types, 73, "butterwell", "RIVERLANDS");
        add(types, 74, "blackwood", "RIVERLANDS");
        add(types, 75, "blackwoodBook", "RIVERLANDS");
        add(types, 76, "bracken", "RIVERLANDS");
        add(types, 77, "brackenBook", "RIVERLANDS");
        add(types, 78, "vypren", "RIVERLANDS");
        add(types, 79, "vanceWR", "RIVERLANDS");
        add(types, 80, "vanceA", "RIVERLANDS");
        add(types, 81, "goodbrook", "RIVERLANDS");
        add(types, 82, "darry", "RIVERLANDS");
        add(types, 83, "lychester", "RIVERLANDS");
        add(types, 84, "mallister", "RIVERLANDS");
        add(types, 85, "jaremymallister", "RIVERLANDS");
        add(types, 86, "mooton", "RIVERLANDS");
        add(types, 87, "piper", "RIVERLANDS");
        add(types, 88, "ryger", "RIVERLANDS");
        add(types, 89, "roote", "RIVERLANDS");
        add(types, 90, "smallwood", "RIVERLANDS");
        add(types, 91, "whent", "RIVERLANDS");
        add(types, 92, "frey", "RIVERLANDS");
        add(types, 93, "freyBook", "RIVERLANDS");
        add(types, 94, "aemonrivers", "RIVERLANDS");
        add(types, 95, "benfrey", "RIVERLANDS");
        add(types, 96, "bigwalder", "RIVERLANDS");
        add(types, 97, "littlewalder", "RIVERLANDS");
        add(types, 98, "walder", "RIVERLANDS");
        add(types, 99, "charlton", "RIVERLANDS");
        add(types, 100, "cox", "RIVERLANDS");
        add(types, 101, "paege", "RIVERLANDS");
        add(types, 102, "wode", "RIVERLANDS");
        add(types, 103, "heddle", "RIVERLANDS");
        add(types, 104, "haigh", "RIVERLANDS");
        add(types, 105, "erenford", "RIVERLANDS");
        add(types, 106, "grell", "RIVERLANDS");
        add(types, 107, "wayn", "RIVERLANDS");
        add(types, 108, "harlton", "RIVERLANDS");
        add(types, 109, "lothston", "RIVERLANDS");
        add(types, 110, "strong", "RIVERLANDS");
        add(types, 111, "blanetree", "RIVERLANDS");
        add(types, 112, "hawick", "RIVERLANDS");
        add(types, 113, "lolliston", "RIVERLANDS");
        add(types, 114, "shawney", "RIVERLANDS");
        add(types, 115, "blackfish", "RIVERLANDS");
        add(types, 116, "blackfishBook", "RIVERLANDS");
        add(types, 556, "justman", "RIVERLANDS");
        add(types, 557, "qoherys", "RIVERLANDS");
        add(types, 558, "towers", "RIVERLANDS");
        add(types, 559, "teague", "RIVERLANDS");
        add(types, 560, "fisher", "RIVERLANDS");
        add(types, 561, "harroway", "RIVERLANDS");
        add(types, 562, "mudd", "RIVERLANDS");
        add(types, 563, "arlan", "RIVERLANDS");
        add(types, 564, "robertblackwood", "RIVERLANDS");
        add(types, 565, "rolandblackwood", "RIVERLANDS");
        add(types, 566, "rogerblackwood", "RIVERLANDS");
        add(types, 498, "hillmen", "HILL_TRIBES");
        add(types, 117, "arryn", "ARRYN");
        add(types, 118, "arrynBook", "ARRYN");
        add(types, 119, "belmore", "ARRYN");
        add(types, 120, "grafton", "ARRYN");
        add(types, 121, "egen", "ARRYN");
        add(types, 122, "elesham", "ARRYN");
        add(types, 123, "corbray", "ARRYN");
        add(types, 124, "corbrayBook", "ARRYN");
        add(types, 125, "coldwater", "ARRYN");
        add(types, 126, "lynderly", "ARRYN");
        add(types, 127, "melcolm", "ARRYN");
        add(types, 128, "redfort", "ARRYN");
        add(types, 129, "royce", "ARRYN");
        add(types, 130, "royceBook", "ARRYN");
        add(types, 131, "royceGM", "ARRYN");
        add(types, 132, "tollett", "ARRYN");
        add(types, 133, "waynwood", "ARRYN");
        add(types, 134, "hunter", "ARRYN");
        add(types, 135, "hersy", "ARRYN");
        add(types, 136, "waxley", "ARRYN");
        add(types, 137, "moore", "ARRYN");
        add(types, 138, "templeton", "ARRYN");
        add(types, 139, "hardyng", "ARRYN");
        add(types, 140, "harroldhardyng", "ARRYN");
        add(types, 141, "shettgtown", "ARRYN");
        add(types, 142, "shettgtower", "ARRYN");
        add(types, 143, "sunderland", "ARRYN");
        add(types, 144, "borrell", "ARRYN");
        add(types, 145, "torrent", "ARRYN");
        add(types, 146, "upcliff", "ARRYN");
        add(types, 147, "arrynGT", "ARRYN");
        add(types, 148, "baelishold", "ARRYN");
        add(types, 149, "breakstone", "ARRYN");
        add(types, 150, "donniger", "ARRYN");
        add(types, 151, "pryor", "ARRYN");
        add(types, 152, "lipps", "ARRYN");
        add(types, 153, "longtorpe", "ARRYN");
        add(types, 154, "ruthermont", "ARRYN");
        add(types, 155, "wydman", "ARRYN");
        add(types, 156, "hugh", "ARRYN");
        add(types, 567, "shell", "ARRYN");
        add(types, 568, "brightstone", "ARRYN");
        add(types, 294, "stannis", "DRAGONSTONE");
        add(types, 295, "stannisBook", "DRAGONSTONE");
        add(types, 296, "velaryon", "DRAGONSTONE");
        add(types, 297, "velaryonBook", "DRAGONSTONE");
        add(types, 298, "baremmon", "DRAGONSTONE");
        add(types, 299, "sunglass", "DRAGONSTONE");
        add(types, 300, "celtigar", "DRAGONSTONE");
        add(types, 301, "massey", "DRAGONSTONE");
        add(types, 302, "florent", "DRAGONSTONE");
        add(types, 303, "florentBook", "DRAGONSTONE");
        add(types, 304, "staunton", "DRAGONSTONE");
        add(types, 305, "follard", "DRAGONSTONE");
        add(types, 306, "chyttering", "DRAGONSTONE");
        add(types, 307, "seaworth", "DRAGONSTONE");
        add(types, 308, "farring", "DRAGONSTONE");
        add(types, 309, "pendragon", "DRAGONSTONE");
        add(types, 310, "alqalis", "DRAGONSTONE");
        add(types, 311, "rambton", "DRAGONSTONE");
        add(types, 312, "horpe", "DRAGONSTONE");
        add(types, 313, "gower", "DRAGONSTONE");
        add(types, 314, "patrek", "DRAGONSTONE");
        add(types, 315, "suggs", "DRAGONSTONE");
        add(types, 316, "rollandStorm", "DRAGONSTONE");
        add(types, 317, "auranewaters", "DRAGONSTONE");
        add(types, 318, "shadrich", "DRAGONSTONE");
        add(types, 578, "oakenfist", "DRAGONSTONE");
        add(types, 579, "seasmoke", "DRAGONSTONE");
        add(types, 319, "robert", "CROWNLANDS");
        add(types, 254, "joffrey", "CROWNLANDS");
        add(types, 255, "hand", "CROWNLANDS");
        add(types, 256, "baelish", "CROWNLANDS");
        add(types, 257, "baelishBook", "CROWNLANDS");
        add(types, 258, "buckwell", "CROWNLANDS");
        add(types, 259, "byrch", "CROWNLANDS");
        add(types, 260, "wendwater", "CROWNLANDS");
        add(types, 261, "mallery", "CROWNLANDS");
        add(types, 262, "manning", "CROWNLANDS");
        add(types, 263, "rikker", "CROWNLANDS");
        add(types, 264, "rosby", "CROWNLANDS");
        add(types, 265, "stokeworth", "CROWNLANDS");
        add(types, 266, "harte", "CROWNLANDS");
        add(types, 267, "hayford", "CROWNLANDS");
        add(types, 268, "chelsted", "CROWNLANDS");
        add(types, 269, "bruneB", "CROWNLANDS");
        add(types, 270, "bruneDD", "CROWNLANDS");
        add(types, 271, "bywater", "CROWNLANDS");
        add(types, 272, "blount", "CROWNLANDS");
        add(types, 273, "gaunt", "CROWNLANDS");
        add(types, 274, "slynt", "CROWNLANDS");
        add(types, 275, "thorne", "CROWNLANDS");
        add(types, 276, "kettleblack", "CROWNLANDS");
        add(types, 277, "boggs", "CROWNLANDS");
        add(types, 278, "cave", "CROWNLANDS");
        add(types, 279, "cressey", "CROWNLANDS");
        add(types, 280, "dargood", "CROWNLANDS");
        add(types, 281, "darke", "CROWNLANDS");
        add(types, 282, "darkwood", "CROWNLANDS");
        add(types, 283, "hardy", "CROWNLANDS");
        add(types, 284, "hogg", "CROWNLANDS");
        add(types, 285, "langward", "CROWNLANDS");
        add(types, 286, "longwaters", "CROWNLANDS");
        add(types, 287, "pyle", "CROWNLANDS");
        add(types, 288, "pyne", "CROWNLANDS");
        add(types, 289, "rollingford", "CROWNLANDS");
        add(types, 290, "bronnBook", "CROWNLANDS");
        add(types, 291, "tallad", "CROWNLANDS");
        add(types, 292, "lothor", "CROWNLANDS");
        add(types, 293, "morros", "CROWNLANDS");
        add(types, 512, "kingsguard", "CROWNLANDS");
        add(types, 546, "darklyn", "CROWNLANDS");
        add(types, 547, "hollard", "CROWNLANDS");
        add(types, 548, "cargyle", "CROWNLANDS");
        add(types, 549, "crabb", "CROWNLANDS");
        add(types, 599, "duncan", "CROWNLANDS");
        add(types, 321, "renly", "STORMLANDS");
        add(types, 320, "robertB", "STORMLANDS");
        add(types, 322, "renlyBook", "STORMLANDS");
        add(types, 323, "buckler", "STORMLANDS");
        add(types, 324, "grandison", "STORMLANDS");
        add(types, 325, "cafferen", "STORMLANDS");
        add(types, 326, "mertyns", "STORMLANDS");
        add(types, 327, "morrigen", "STORMLANDS");
        add(types, 328, "penrose", "STORMLANDS");
        add(types, 329, "staedmon", "STORMLANDS");
        add(types, 330, "tarth", "STORMLANDS");
        add(types, 331, "tarthBook", "STORMLANDS");
        add(types, 332, "wylde", "STORMLANDS");
        add(types, 333, "fell", "STORMLANDS");
        add(types, 334, "errol", "STORMLANDS");
        add(types, 335, "estermont", "STORMLANDS");
        add(types, 336, "dondarrion", "STORMLANDS");
        add(types, 337, "dondarrionBook", "STORMLANDS");
        add(types, 338, "caron", "STORMLANDS");
        add(types, 339, "swann", "STORMLANDS");
        add(types, 340, "swannBook", "STORMLANDS");
        add(types, 341, "selmy", "STORMLANDS");
        add(types, 342, "bolling", "STORMLANDS");
        add(types, 343, "connington", "STORMLANDS");
        add(types, 344, "hasty", "STORMLANDS");
        add(types, 345, "wagstaff", "STORMLANDS");
        add(types, 346, "wensington", "STORMLANDS");
        add(types, 347, "peasebury", "STORMLANDS");
        add(types, 348, "rogers", "STORMLANDS");
        add(types, 349, "footeN", "STORMLANDS");
        add(types, 350, "trant", "STORMLANDS");
        add(types, 351, "herston", "STORMLANDS");
        add(types, 352, "kellington", "STORMLANDS");
        add(types, 353, "lonmouth", "STORMLANDS");
        add(types, 354, "musgood", "STORMLANDS");
        add(types, 355, "swygert", "STORMLANDS");
        add(types, 356, "tudbury", "STORMLANDS");
        add(types, 357, "whitehead", "STORMLANDS");
        add(types, 358, "pearse", "STORMLANDS");
        add(types, 359, "edricstorm", "STORMLANDS");
        add(types, 513, "renlyguard", "STORMLANDS");
        add(types, 580, "durrandon", "STORMLANDS");
        add(types, 581, "cole", "STORMLANDS");
        add(types, 582, "toyne", "STORMLANDS");
        add(types, 360, "tyrell", "REACH");
        add(types, 415, "durwell", "REACH");
        add(types, 361, "ambrose", "REACH");
        add(types, 362, "blackbar", "REACH");
        add(types, 363, "varner", "REACH");
        add(types, 364, "vyrwel", "REACH");
        add(types, 365, "caswell", "REACH");
        add(types, 366, "cordwayner", "REACH");
        add(types, 367, "cockshaw", "REACH");
        add(types, 368, "crane", "REACH");
        add(types, 369, "meadows", "REACH");
        add(types, 370, "merryweather", "REACH");
        add(types, 371, "oakheart", "REACH");
        add(types, 372, "peake", "REACH");
        add(types, 373, "redwyne", "REACH");
        add(types, 374, "redwyneBook", "REACH");
        add(types, 375, "rowan", "REACH");
        add(types, 376, "tarly", "REACH");
        add(types, 377, "tarlyBook", "REACH");
        add(types, 378, "tyrellBK", "REACH");
        add(types, 379, "tyrelll", "REACH");
        add(types, 380, "fossowayCH", "REACH");
        add(types, 381, "footly", "REACH");
        add(types, 382, "hightower", "REACH");
        add(types, 383, "hightowerBook", "REACH");
        add(types, 384, "shermer", "REACH");
        add(types, 385, "appleton", "REACH");
        add(types, 386, "ashford", "REACH");
        add(types, 387, "beesbury", "REACH");
        add(types, 388, "bullwer", "REACH");
        add(types, 389, "costayne", "REACH");
        add(types, 390, "cuy", "REACH");
        add(types, 391, "mullendore", "REACH");
        add(types, 392, "grimm", "REACH");
        add(types, 393, "serry", "REACH");
        add(types, 394, "hewett", "REACH");
        add(types, 395, "chester", "REACH");
        add(types, 396, "fossowayNB", "REACH");
        add(types, 397, "osgrey", "REACH");
        add(types, 398, "osgreyll", "REACH");
        add(types, 399, "ball", "REACH");
        add(types, 400, "webber", "REACH");
        add(types, 401, "willum", "REACH");
        add(types, 402, "woodwright", "REACH");
        add(types, 403, "graceford", "REACH");
        add(types, 404, "inchfield", "REACH");
        add(types, 405, "leygood", "REACH");
        add(types, 406, "kidwell", "REACH");
        add(types, 407, "norcross", "REACH");
        add(types, 408, "risley", "REACH");
        add(types, 409, "roxton", "REACH");
        add(types, 410, "wythers", "REACH");
        add(types, 411, "hunt", "REACH");
        add(types, 412, "bridges", "REACH");
        add(types, 413, "bushy", "REACH");
        add(types, 414, "dunn", "REACH");
        add(types, 416, "hastwyck", "REACH");
        add(types, 417, "hutcheson", "REACH");
        add(types, 418, "lowther", "REACH");
        add(types, 419, "lyberr", "REACH");
        add(types, 420, "morgryn", "REACH");
        add(types, 421, "norridge", "REACH");
        add(types, 423, "orme", "REACH");
        add(types, 424, "overton", "REACH");
        add(types, 425, "pommingham", "REACH");
        add(types, 426, "rhysling", "REACH");
        add(types, 427, "sloane", "REACH");
        add(types, 428, "stackhouse", "REACH");
        add(types, 430, "westbrook", "REACH");
        add(types, 431, "whitegrove", "REACH");
        add(types, 432, "bronn", "REACH");
        add(types, 583, "gardener", "REACH");
        add(types, 584, "gardenerBook", "REACH");
        add(types, 585, "fireball", "REACH");
        add(types, 586, "strickland", "REACH");
        add(types, 587, "robertashford", "REACH");
        add(types, 588, "bennis", "REACH");
        add(types, 589, "derrickfossoway", "REACH");
        add(types, 433, "martell", "DORNE");
        add(types, 434, "martellBook", "DORNE");
        add(types, 435, "oberyn", "DORNE");
        add(types, 436, "sandsnakes", "DORNE");
        add(types, 437, "yronwood", "DORNE");
        add(types, 438, "allyrion", "DORNE");
        add(types, 439, "blackmont", "DORNE");
        add(types, 440, "vaith", "DORNE");
        add(types, 441, "wyl", "DORNE");
        add(types, 442, "gargalen", "DORNE");
        add(types, 443, "dayne", "DORNE");
        add(types, 444, "jordayne", "DORNE");
        add(types, 445, "qorgile", "DORNE");
        add(types, 446, "manwoody", "DORNE");
        add(types, 447, "toland", "DORNE");
        add(types, 448, "uller", "DORNE");
        add(types, 449, "fowler", "DORNE");
        add(types, 450, "fowlerBook", "DORNE");
        add(types, 451, "dalt", "DORNE");
        add(types, 452, "dayneHH", "DORNE");
        add(types, 453, "santagar", "DORNE");
        add(types, 454, "drinkwater", "DORNE");
        add(types, 455, "ladybright", "DORNE");
        add(types, 456, "tarwick", "DORNE");
        add(types, 457, "wellsD", "DORNE");
        add(types, 590, "mors", "DORNE");
        add(types, 591, "morsBook", "DORNE");
        add(types, 592, "nymeria", "DORNE");
        add(types, 593, "dryland", "DORNE");
        add(types, 594, "vultureking", "DORNE");
        add(types, 458, "braavos", "BRAAVOS");
        add(types, 459, "iron_bank", "BRAAVOS");
        add(types, 469, "volantis", "VOLANTIS");
        add(types, 470, "tigers", "VOLANTIS");
        add(types, 471, "elephants", "VOLANTIS");
        add(types, 460, "pentos", "PENTOS");
        add(types, 461, "mopatis", "PENTOS");
        add(types, 467, "norvos", "NORVOS");
        add(types, 462, "lorath", "LORATH");
        add(types, 466, "qohor", "QOHOR");
        add(types, 464, "lys", "LYS");
        add(types, 465, "saan", "LYS");
        add(types, 463, "myr", "MYR");
        add(types, 468, "tyrosh", "TYROSH");
        add(types, 473, "ghiscar", "GHISCAR");
        add(types, 474, "astapor", "GHISCAR");
        add(types, 475, "yunkai", "GHISCAR");
        add(types, 476, "meereen", "GHISCAR");
        add(types, 477, "newghis", "GHISCAR");
        add(types, 478, "loraq", "GHISCAR");
        add(types, 479, "qarth", "QARTH");
        add(types, 472, "lhazar", "LHAZAR");
        add(types, 480, "ibben", "IBBEN");
        add(types, 616, "jogos_nhai", "JOGOS_NHAI");
        add(types, 615, "mossovy", "MOSSOVY");
        add(types, 482, "yi_ti", "YI_TI");
        add(types, 483, "yi_ti_bu", "YI_TI");
        add(types, 484, "yi_ti_choq", "YI_TI");
        add(types, 485, "yi_ti_har", "YI_TI");
        add(types, 486, "yi_ti_jar", "YI_TI");
        add(types, 487, "yi_ti_lo", "YI_TI");
        add(types, 488, "yi_ti_maroon", "YI_TI");
        add(types, 489, "yi_ti_mengo", "YI_TI");
        add(types, 490, "yi_ti_pearl", "YI_TI");
        add(types, 491, "yi_ti_purple", "YI_TI");
        add(types, 492, "yi_ti_qo", "YI_TI");
        add(types, 493, "leng", "YI_TI");
        add(types, 614, "asshai", "ASSHAI");
        add(types, 481, "summer", "SUMMER_ISLANDS");
        add(types, 494, "sothoryos", "SOTHORYOS");
        add(types, 244, "cleos", "UNALIGNED");
        add(types, 500, "sparrow", "UNALIGNED");
        add(types, 501, "maesters", "UNALIGNED");
        add(types, 502, "secondsons", "UNALIGNED");
        add(types, 503, "golden_company", "UNALIGNED");
        add(types, 504, "windblown", "UNALIGNED");
        add(types, 505, "stormcrows", "UNALIGNED");
        add(types, 506, "bravecompanions", "UNALIGNED");
        add(types, 507, "warriorsSons", "UNALIGNED");
        add(types, 508, "poorFellows", "UNALIGNED");
        add(types, 509, "andal", "UNALIGNED");
        add(types, 510, "sept", "UNALIGNED");
        add(types, 511, "faceless", "UNALIGNED");
        add(types, 514, "brotherhood", "UNALIGNED");
        add(types, 515, "rhllor", "UNALIGNED");
        add(types, 516, "white", "UNALIGNED");
        add(types, 517, "targaryen", "UNALIGNED");
        add(types, 518, "targaryenBook", "UNALIGNED");
        add(types, 519, "blackfyre", "UNALIGNED");
        add(types, 520, "blackfyreBook", "UNALIGNED");
        add(types, 521, "blacks", "UNALIGNED");
        add(types, 522, "blacksBook", "UNALIGNED");
        add(types, 523, "greens", "UNALIGNED");
        add(types, 524, "greensBook", "UNALIGNED");
        add(types, 525, "aemon", "UNALIGNED");
        add(types, 526, "aemonBook", "UNALIGNED");
        add(types, 527, "aerion", "UNALIGNED");
        add(types, 528, "aerionBook", "UNALIGNED");
        add(types, 529, "valarr", "UNALIGNED");
        add(types, 530, "valarrBook", "UNALIGNED");
        add(types, 531, "bittersteel", "UNALIGNED");
        add(types, 532, "bloodraven", "UNALIGNED");
        add(types, 533, "bloodravenBook", "UNALIGNED");
        add(types, 534, "seastar", "UNALIGNED");
        add(types, 535, "maekar", "UNALIGNED");
        add(types, 536, "maekarBook", "UNALIGNED");
        add(types, 537, "daemon", "UNALIGNED");
        add(types, 538, "truefyre", "UNALIGNED");
        add(types, 539, "daeron", "UNALIGNED");
        add(types, 540, "daeronBook", "UNALIGNED");
        add(types, 541, "rhaegar", "UNALIGNED");
        add(types, 542, "youngGriff", "UNALIGNED");
        add(types, 543, "jonconnington", "UNALIGNED");
        add(types, 544, "underleaf", "UNALIGNED");
        add(types, 545, "rossart", "UNALIGNED");
        add(types, 595, "belaerys", "UNALIGNED");
        add(types, 596, "galtry", "UNALIGNED");
        add(types, 597, "illifer", "UNALIGNED");
        add(types, 598, "creighton", "UNALIGNED");
        add(types, 601, "leather", "UNALIGNED");
        add(types, 617, "null", "UNALIGNED");
        return List.copyOf(types);
    }

    private static void add(List<GOTBannerType> types, int legacyId, String name, String faction) {
        types.add(new GOTBannerType(legacyId, name, faction));
    }

    private static Map<Integer, GOTBannerType> indexById() {
        LinkedHashMap<Integer, GOTBannerType> result = new LinkedHashMap<>();
        for (GOTBannerType type : VALUES) {
            if (result.put(type.legacyId, type) != null) {
                throw new IllegalStateException("Duplicate legacy banner ID " + type.legacyId);
            }
        }
        return Map.copyOf(result);
    }

    private static Map<String, GOTBannerType> indexByName() {
        LinkedHashMap<String, GOTBannerType> result = new LinkedHashMap<>();
        for (GOTBannerType type : VALUES) {
            if (result.put(type.name, type) != null) {
                throw new IllegalStateException("Duplicate banner name " + type.name);
            }
        }
        return Map.copyOf(result);
    }
}
