package got;
import got.achievement.GOTAchievementHooks;
import net.minecraft.ChatFormatting;import net.minecraft.core.BlockPos;import net.minecraft.network.chat.Component;import net.minecraft.server.level.ServerPlayer;import net.minecraft.tags.BlockTags;import net.minecraft.world.InteractionHand;import net.minecraft.world.InteractionResult;import net.minecraft.world.InteractionResultHolder;import net.minecraft.world.entity.LivingEntity;import net.minecraft.world.entity.animal.Animal;import net.minecraft.world.entity.player.Player;import net.minecraft.world.item.Item;import net.minecraft.world.item.ItemStack;import net.minecraft.world.item.TooltipFlag;import net.minecraft.world.item.context.UseOnContext;import net.minecraft.world.level.Level;import net.minecraft.world.level.block.AbstractFurnaceBlock;import net.minecraft.world.level.block.CampfireBlock;import net.minecraft.world.level.block.state.BlockState;import org.jetbrains.annotations.Nullable;import java.util.List;
public final class GOTBrandingIronItem extends Item{
 public static final String BRAND="BrandName",HOT="HotIron",BRANDER="GOTBrander";public GOTBrandingIronItem(Properties p){super(p.stacksTo(1).durability(100));}
 public static String brand(ItemStack s){return s.hasTag()?s.getTag().getString(BRAND):"";}public static boolean hot(ItemStack s){return s.hasTag()&&s.getTag().getBoolean(HOT);}public static void setBrand(ItemStack s,String n){n=n==null?"":n.trim();if(n.length()>64)n=n.substring(0,64);s.getOrCreateTag().putString(BRAND,n);}public static void setHot(ItemStack s,boolean b){s.getOrCreateTag().putBoolean(HOT,b);}
 @Override public InteractionResultHolder<ItemStack> use(Level l,Player p,InteractionHand h){ItemStack s=p.getItemInHand(h);if(l.isClientSide&&brand(s).isBlank()) net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(net.minecraftforge.api.distmarker.Dist.CLIENT, () -> () -> got.client.GOTBrandingIronScreen.open(h));return InteractionResultHolder.sidedSuccess(s,l.isClientSide);}
 @Override public InteractionResult interactLivingEntity(ItemStack s,Player p,LivingEntity target,InteractionHand h){if(!(target instanceof Animal)||!hot(s)||brand(s).isBlank())return InteractionResult.PASS;if(!p.level().isClientSide){target.setCustomName(Component.literal(brand(s)));target.setCustomNameVisible(false);((Animal)target).setPersistenceRequired();target.getPersistentData().putUUID(BRANDER,p.getUUID());int before=s.getDamageValue();s.hurtAndBreak(1,p,x->x.broadcastBreakEvent(h));if(before/5!=s.getDamageValue()/5)setHot(s,false);if(p instanceof ServerPlayer sp)GOTAchievementHooks.award(sp,"BRAND_ENTITY");}return InteractionResult.sidedSuccess(p.level().isClientSide);}
 @Override public InteractionResult useOn(UseOnContext c){ItemStack s=c.getItemInHand();if(brand(s).isBlank()||hot(s))return InteractionResult.PASS;Level l=c.getLevel();BlockState st=l.getBlockState(c.getClickedPos());boolean heat=(st.getBlock() instanceof AbstractFurnaceBlock&&st.hasProperty(net.minecraft.world.level.block.state.properties.BlockStateProperties.LIT)&&st.getValue(net.minecraft.world.level.block.state.properties.BlockStateProperties.LIT))||(st.getBlock() instanceof CampfireBlock&&st.hasProperty(net.minecraft.world.level.block.state.properties.BlockStateProperties.LIT)&&st.getValue(net.minecraft.world.level.block.state.properties.BlockStateProperties.LIT))||st.is(net.minecraft.world.level.block.Blocks.FIRE)||st.is(net.minecraft.world.level.block.Blocks.SOUL_FIRE)||st.is(net.minecraft.world.level.block.Blocks.LAVA)||(st.is(GOTBlocks.ALLOY_FORGE.get())&&st.hasProperty(AlloyForgeBlock.LIT)&&st.getValue(AlloyForgeBlock.LIT))||(st.is(GOTBlocks.OVEN.get())&&st.hasProperty(OvenBlock.LIT)&&st.getValue(OvenBlock.LIT));if(!heat){BlockPos q=c.getClickedPos().relative(c.getClickedFace());BlockState a=l.getBlockState(q);heat=a.is(net.minecraft.world.level.block.Blocks.FIRE)||a.is(net.minecraft.world.level.block.Blocks.SOUL_FIRE)||a.is(net.minecraft.world.level.block.Blocks.LAVA);}if(heat&&!l.isClientSide)setHot(s,true);return heat?InteractionResult.sidedSuccess(l.isClientSide):InteractionResult.PASS;}
 @Override public boolean isFoil(ItemStack s){return hot(s)||super.isFoil(s);}@Override public void appendHoverText(ItemStack s,@Nullable Level l,List<Component> out,TooltipFlag f){String b=brand(s);out.add(Component.translatable(b.isBlank()?"item.got.brandingIron.unnamed":"item.got.brandingIron.named",b).withStyle(ChatFormatting.GRAY));if(hot(s))out.add(Component.translatable("item.got.brandingIron.hot").withStyle(ChatFormatting.RED));}
}
