package got;

public enum GOTSmithingEffect {
    DAMAGE_ADD,
    DURABILITY_FACTOR,
    MELEE_SPEED_FACTOR,
    MELEE_REACH_FACTOR,
    KNOCKBACK_ADD,
    TOOL_SPEED_FACTOR,
    SILK_TOUCH,
    LOOTING_ADD,
    ARMOR_PROTECTION_ADD,
    FIRE_PROTECTION_ADD,
    FALL_PROTECTION_ADD,
    RANGED_PROTECTION_ADD,
    RANGED_DAMAGE_FACTOR,
    RANGED_KNOCKBACK_ADD,
    FIRE_ON_HIT,
    CHILL_ON_HIT,
    HEADHUNTING
}
