package got;
import net.minecraft.sounds.SoundEvents;import net.minecraft.sounds.SoundSource;import net.minecraft.world.InteractionHand;import net.minecraft.world.InteractionResultHolder;import net.minecraft.world.entity.LivingEntity;import net.minecraft.world.entity.player.Player;import net.minecraft.world.item.Item;import net.minecraft.world.item.ItemStack;import net.minecraft.world.item.UseAnim;import net.minecraft.world.level.Level;
public final class GOTSarbacaneItem extends Item{
 public GOTSarbacaneItem(Properties p){super(p.stacksTo(1).durability(250));}
 public UseAnim getUseAnimation(ItemStack s){return UseAnim.BOW;}public int getUseDuration(ItemStack s){return 72000;}
 public InteractionResultHolder<ItemStack> use(Level l,Player p,InteractionHand h){ItemStack s=p.getItemInHand(h);if(p.getAbilities().instabuild||findAmmo(p)>=0){p.startUsingItem(h);return InteractionResultHolder.consume(s);}return InteractionResultHolder.fail(s);}
 public void releaseUsing(ItemStack tube,Level l,LivingEntity user,int left){if(!(user instanceof Player p))return;int charge=getUseDuration(tube)-left;float f=charge/5F;if(f<.65F)return;f=Math.min(1F,f*(f+2F)/3F);int slot=findAmmo(p);boolean poison=false;if(slot<0&&!p.getAbilities().instabuild)return;if(slot>=0){ItemStack a=p.getInventory().getItem(slot);poison=a.is(GOTEquipment.DART_POISONED.get());if(!p.getAbilities().instabuild){a.shrink(1);if(a.isEmpty())p.getInventory().setItem(slot,ItemStack.EMPTY);}}tube.hurtAndBreak(1,p,x->x.broadcastBreakEvent(p.getUsedItemHand()));if(!l.isClientSide){GOTDartEntity d=new GOTDartEntity(l,p,poison);d.shootFromRotation(p,p.getXRot(),p.getYRot(),0,f*2F,1F);l.addFreshEntity(d);l.playSound(null,p.blockPosition(),SoundEvents.ARROW_SHOOT,SoundSource.PLAYERS,1F,1.0F+f*.5F);got.achievement.GOTAchievementHooks.award((net.minecraft.server.level.ServerPlayer)p,"USE_SARBACANE");}}
 private static int findAmmo(Player p){for(int i=0;i<p.getInventory().getContainerSize();i++){ItemStack s=p.getInventory().getItem(i);if(s.is(GOTEquipment.DART.get())||s.is(GOTEquipment.DART_POISONED.get()))return i;}return -1;}
}
