package got.world.biome;

import got.GOTMod;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.biome.Biome;
import java.util.*;

/** Complete modern registry foundation for every original GOTBiome static entry. */
public final class GOTBiomes {
    private static final Map<String, ResourceKey<Biome>> BY_ID = new LinkedHashMap<>();
    private static final Map<String, GOTBiomeMetadata> METADATA = new LinkedHashMap<>();
    public static final ResourceKey<Biome> ALWAYS_WINTER = register("always_winter", GOTBiomePreset.FROST);
    public static final ResourceKey<Biome> ARRYN = register("arryn", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> ARRYN_FOREST = register("arryn_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> ARRYN_MOUNTAINS = register("arryn_mountains", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> ARRYN_MOUNTAINS_FOOTHILLS = register("arryn_mountains_foothills", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> ARRYN_TOWN = register("arryn_town", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> BEACH = register("beach", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> BEACH_GRAVEL = register("beach_gravel", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> BEACH_WHITE = register("beach_white", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> BLEEDING_BEACH = register("bleeding_beach", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> BLEEDING_SEA = register("bleeding_sea", GOTBiomePreset.AQUATIC);
    public static final ResourceKey<Biome> BONE_MOUNTAINS = register("bone_mountains", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> BRAAVOS = register("braavos", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> BRAAVOS_FOREST = register("braavos_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> BRAAVOS_HILLS = register("braavos_hills", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> CANNIBAL_SANDS = register("cannibal_sands", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> CANNIBAL_SANDS_HILLS = register("cannibal_sands_hills", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> FROZEN_SHORE = register("frozen_shore", GOTBiomePreset.FROST);
    public static final ResourceKey<Biome> CROWNLANDS = register("crownlands", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> CROWNLANDS_FOREST = register("crownlands_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> CROWNLANDS_TOWN = register("crownlands_town", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> DISPUTED_LANDS = register("disputed_lands", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> DISPUTED_LANDS_FOREST = register("disputed_lands_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> DORNE = register("dorne", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> DORNE_DESERT = register("dorne_desert", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> DORNE_FOREST = register("dorne_forest", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> DORNE_MESA = register("dorne_mesa", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> DORNE_MOUNTAINS = register("dorne_mountains", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> DOTHRAKI_SEA = register("dothraki_sea", GOTBiomePreset.SAVANNAH);
    public static final ResourceKey<Biome> DOTHRAKI_SEA_FOREST = register("dothraki_sea_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> DOTHRAKI_SEA_HILLS = register("dothraki_sea_hills", GOTBiomePreset.SAVANNAH);
    public static final ResourceKey<Biome> DRAGONSTONE = register("dragonstone", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> ESSOS = register("essos", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> ESSOS_FOREST = register("essos_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> ESSOS_MARSHES = register("essos_marshes", GOTBiomePreset.MARSHES);
    public static final ResourceKey<Biome> ESSOS_MOUNTAINS = register("essos_mountains", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> FROSTFANGS = register("frostfangs", GOTBiomePreset.FROST);
    public static final ResourceKey<Biome> GHISCAR = register("ghiscar", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> GHISCAR_ASTAPOR = register("ghiscar_astapor", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> GHISCAR_COLONY = register("ghiscar_colony", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> GHISCAR_FOREST = register("ghiscar_forest", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> GHISCAR_MEEREEN = register("ghiscar_meereen", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> GHISCAR_NEW_GHIS = register("ghiscar_new_ghis", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> GHISCAR_YUNKAI = register("ghiscar_yunkai", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> GIFT_NEW = register("gift_new", GOTBiomePreset.NORTHERN_PLAINS);
    public static final ResourceKey<Biome> GIFT_OLD = register("gift_old", GOTBiomePreset.NORTHERN_PLAINS);
    public static final ResourceKey<Biome> HAUNTED_FOREST = register("haunted_forest", GOTBiomePreset.TAIGA);
    public static final ResourceKey<Biome> IBBEN = register("ibben", GOTBiomePreset.NORTHERN_PLAINS);
    public static final ResourceKey<Biome> IBBEN_COLONY = register("ibben_colony", GOTBiomePreset.NORTHERN_PLAINS);
    public static final ResourceKey<Biome> IBBEN_COLONY_FOREST = register("ibben_colony_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> IBBEN_COLONY_HILLS = register("ibben_colony_hills", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> IBBEN_MOUNTAINS = register("ibben_mountains", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> IBBEN_TAIGA = register("ibben_taiga", GOTBiomePreset.TAIGA);
    public static final ResourceKey<Biome> IFEKEVRON_FOREST = register("ifekevron_forest", GOTBiomePreset.TAIGA);
    public static final ResourceKey<Biome> IRON_ISLANDS = register("iron_islands", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> IRON_ISLANDS_FOREST = register("iron_islands_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> IRON_ISLANDS_HILLS = register("iron_islands_hills", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> ISLAND = register("island", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> ISLE_OF_FACES = register("isle_of_faces", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> JOGOS_NHAI = register("jogos_nhai", GOTBiomePreset.SAVANNAH);
    public static final ResourceKey<Biome> JOGOS_NHAI_DESERT = register("jogos_nhai_desert", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> JOGOS_NHAI_DESERT_HILLS = register("jogos_nhai_desert_hills", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> JOGOS_NHAI_FOREST = register("jogos_nhai_forest", GOTBiomePreset.SAVANNAH);
    public static final ResourceKey<Biome> JOGOS_NHAI_HILLS = register("jogos_nhai_hills", GOTBiomePreset.SAVANNAH);
    public static final ResourceKey<Biome> KING_SPEARS = register("king_spears", GOTBiomePreset.AQUATIC);
    public static final ResourceKey<Biome> KINGSWOOD_NORTH = register("kingswood_north", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> KINGSWOOD_SOUTH = register("kingswood_south", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> LAKE = register("lake", GOTBiomePreset.AQUATIC);
    public static final ResourceKey<Biome> LHAZAR = register("lhazar", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> LHAZAR_FOREST = register("lhazar_forest", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> LHAZAR_HILLS = register("lhazar_hills", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> LONG_SUMMER = register("long_summer", GOTBiomePreset.SAVANNAH);
    public static final ResourceKey<Biome> LORATH = register("lorath", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> LORATH_FOREST = register("lorath_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> LORATH_HILLS = register("lorath_hills", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> LORATH_MAZE = register("lorath_maze", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> LYS = register("lys", GOTBiomePreset.SOUTHERN_PLAINS);
    public static final ResourceKey<Biome> MASSY = register("massy", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> MASSY_HILLS = register("massy_hills", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> MOSSOVY = register("mossovy", GOTBiomePreset.NORTHERN_PLAINS);
    public static final ResourceKey<Biome> MOSSOVY_MARSHES = register("mossovy_marshes", GOTBiomePreset.MARSHES);
    public static final ResourceKey<Biome> MOSSOVY_MOUNTAINS = register("mossovy_mountains", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> MOSSOVY_TAIGA = register("mossovy_taiga", GOTBiomePreset.TAIGA);
    public static final ResourceKey<Biome> MYR = register("myr", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> MYR_FOREST = register("myr_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> NAATH = register("naath", GOTBiomePreset.SOUTHERN_PLAINS);
    public static final ResourceKey<Biome> NECK = register("neck", GOTBiomePreset.MARSHES);
    public static final ResourceKey<Biome> NECK_FOREST = register("neck_forest", GOTBiomePreset.MARSHES);
    public static final ResourceKey<Biome> NORTH = register("north", GOTBiomePreset.NORTHERN_PLAINS);
    public static final ResourceKey<Biome> NORTH_BARROWS = register("north_barrows", GOTBiomePreset.NORTHERN_PLAINS);
    public static final ResourceKey<Biome> NORTH_FOREST = register("north_forest", GOTBiomePreset.TAIGA);
    public static final ResourceKey<Biome> NORTH_FOREST_IRONTREE = register("north_forest_irontree", GOTBiomePreset.TAIGA);
    public static final ResourceKey<Biome> NORTH_HILLS = register("north_hills", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> NORTH_MOUNTAINS = register("north_mountains", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> NORTH_TOWN = register("north_town", GOTBiomePreset.NORTHERN_PLAINS);
    public static final ResourceKey<Biome> NORTH_WILD = register("north_wild", GOTBiomePreset.NORTHERN_PLAINS);
    public static final ResourceKey<Biome> NORVOS = register("norvos", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> NORVOS_FOREST = register("norvos_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> NORVOS_HILLS = register("norvos_hills", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> OCEAN1 = register("ocean1", GOTBiomePreset.AQUATIC);
    public static final ResourceKey<Biome> OCEAN2 = register("ocean2", GOTBiomePreset.AQUATIC);
    public static final ResourceKey<Biome> OCEAN3 = register("ocean3", GOTBiomePreset.AQUATIC);
    public static final ResourceKey<Biome> OCEAN = register("ocean", GOTBiomePreset.AQUATIC);
    public static final ResourceKey<Biome> PENTOS = register("pentos", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> PENTOS_FOREST = register("pentos_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> PENTOS_HILLS = register("pentos_hills", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> QARTH = register("qarth", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> QARTH_COLONY = register("qarth_colony", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> QARTH_DESERT = register("qarth_desert", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> QOHOR = register("qohor", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> QOHOR_FOREST = register("qohor_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> QOHOR_HILLS = register("qohor_hills", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> REACH = register("reach", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> REACH_ARBOR = register("reach_arbor", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> REACH_FIRE_FIELD = register("reach_fire_field", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> REACH_FOREST = register("reach_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> REACH_HILLS = register("reach_hills", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> REACH_TOWN = register("reach_town", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> RIVER = register("river", GOTBiomePreset.AQUATIC);
    public static final ResourceKey<Biome> RIVERLANDS = register("riverlands", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> RIVERLANDS_FOREST = register("riverlands_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> SHADOW_LAND = register("shadow_land", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> SHADOW_MOUNTAINS = register("shadow_mountains", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> SHADOW_TOWN = register("shadow_town", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> SHRYKES_LAND = register("shrykes_land", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> SKAGOS = register("skagos", GOTBiomePreset.NORTHERN_PLAINS);
    public static final ResourceKey<Biome> SKIRLING_PASS = register("skirling_pass", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> SOTHORYOS_BUSHLAND = register("sothoryos_bushland", GOTBiomePreset.SAVANNAH);
    public static final ResourceKey<Biome> SOTHORYOS_DESERT = register("sothoryos_desert", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> SOTHORYOS_DESERT_COLD = register("sothoryos_desert_cold", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> SOTHORYOS_DESERT_HILLS = register("sothoryos_desert_hills", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> SOTHORYOS_FOREST = register("sothoryos_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> SOTHORYOS_FROST = register("sothoryos_frost", GOTBiomePreset.FROST);
    public static final ResourceKey<Biome> SOTHORYOS_HELL = register("sothoryos_hell", GOTBiomePreset.SOUTHERN_PLAINS);
    public static final ResourceKey<Biome> SOTHORYOS_JUNGLE = register("sothoryos_jungle", GOTBiomePreset.JUNGLE);
    public static final ResourceKey<Biome> SOTHORYOS_JUNGLE_EDGE = register("sothoryos_jungle_edge", GOTBiomePreset.JUNGLE);
    public static final ResourceKey<Biome> SOTHORYOS_MANGROVE = register("sothoryos_mangrove", GOTBiomePreset.JUNGLE);
    public static final ResourceKey<Biome> SOTHORYOS_MOUNTAINS = register("sothoryos_mountains", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> SOTHORYOS_SAVANNAH = register("sothoryos_savannah", GOTBiomePreset.SAVANNAH);
    public static final ResourceKey<Biome> SOTHORYOS_TAIGA = register("sothoryos_taiga", GOTBiomePreset.TAIGA);
    public static final ResourceKey<Biome> SOTHORYOS_TAIGA_EDGE = register("sothoryos_taiga_edge", GOTBiomePreset.TAIGA);
    public static final ResourceKey<Biome> STEPSTONES = register("stepstones", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> STONEY_SHORE = register("stoney_shore", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> STORMLANDS = register("stormlands", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> STORMLANDS_FOREST = register("stormlands_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> STORMLANDS_TARTH = register("stormlands_tarth", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> STORMLANDS_TARTH_FOREST = register("stormlands_tarth_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> STORMLANDS_TOWN = register("stormlands_town", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> SUMMER_COLONY = register("summer_colony", GOTBiomePreset.SOUTHERN_PLAINS);
    public static final ResourceKey<Biome> SUMMER_ISLANDS = register("summer_islands", GOTBiomePreset.SOUTHERN_PLAINS);
    public static final ResourceKey<Biome> SUMMER_ISLANDS_TROPICAL_FOREST = register("summer_islands_tropical_forest", GOTBiomePreset.JUNGLE);
    public static final ResourceKey<Biome> THENN_LAND = register("thenn_land", GOTBiomePreset.NORTHERN_PLAINS);
    public static final ResourceKey<Biome> TYROSH = register("tyrosh", GOTBiomePreset.SOUTHERN_PLAINS);
    public static final ResourceKey<Biome> ULTHOS_BUSHLAND = register("ulthos_bushland", GOTBiomePreset.SAVANNAH);
    public static final ResourceKey<Biome> ULTHOS_DESERT = register("ulthos_desert", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> ULTHOS_DESERT_COLD = register("ulthos_desert_cold", GOTBiomePreset.DESERT);
    public static final ResourceKey<Biome> ULTHOS_FOREST = register("ulthos_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> ULTHOS_FOREST_EDGE = register("ulthos_forest_edge", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> ULTHOS_FROST = register("ulthos_frost", GOTBiomePreset.FROST);
    public static final ResourceKey<Biome> ULTHOS_MARSHES = register("ulthos_marshes", GOTBiomePreset.MARSHES);
    public static final ResourceKey<Biome> ULTHOS_MARSHES_FOREST = register("ulthos_marshes_forest", GOTBiomePreset.MARSHES);
    public static final ResourceKey<Biome> ULTHOS_MOUNTAINS = register("ulthos_mountains", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> ULTHOS_RED_FOREST = register("ulthos_red_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> ULTHOS_RED_FOREST_EDGE = register("ulthos_red_forest_edge", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> ULTHOS_TAIGA = register("ulthos_taiga", GOTBiomePreset.TAIGA);
    public static final ResourceKey<Biome> ULTHOS_TAIGA_EDGE = register("ulthos_taiga_edge", GOTBiomePreset.TAIGA);
    public static final ResourceKey<Biome> VALYRIA = register("valyria", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> VALYRIA_SEA = register("valyria_sea", GOTBiomePreset.AQUATIC);
    public static final ResourceKey<Biome> VALYRIA_SEA1 = register("valyria_sea1", GOTBiomePreset.AQUATIC);
    public static final ResourceKey<Biome> VALYRIA_SEA2 = register("valyria_sea2", GOTBiomePreset.AQUATIC);
    public static final ResourceKey<Biome> VALYRIA_VOLCANO = register("valyria_volcano", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> VOLANTIS = register("volantis", GOTBiomePreset.SOUTHERN_PLAINS);
    public static final ResourceKey<Biome> VOLANTIS_FOREST = register("volantis_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> VOLANTIS_MARSHES = register("volantis_marshes", GOTBiomePreset.MARSHES);
    public static final ResourceKey<Biome> VOLANTIS_ORANGE_FOREST = register("volantis_orange_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> WESTERLANDS = register("westerlands", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> WESTERLANDS_FOREST = register("westerlands_forest", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> WESTERLANDS_HILLS = register("westerlands_hills", GOTBiomePreset.MOUNTAINS);
    public static final ResourceKey<Biome> WESTERLANDS_TOWN = register("westerlands_town", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> WESTEROS_FROST = register("westeros_frost", GOTBiomePreset.FROST);
    public static final ResourceKey<Biome> WHISPERING_WOOD = register("whispering_wood", GOTBiomePreset.FOREST);
    public static final ResourceKey<Biome> WOLFSWOOD = register("wolfswood", GOTBiomePreset.TAIGA);
    public static final ResourceKey<Biome> YEEN = register("yeen", GOTBiomePreset.MIDERATE_PLAINS);
    public static final ResourceKey<Biome> YI_TI = register("yi_ti", GOTBiomePreset.SOUTHERN_PLAINS);
    public static final ResourceKey<Biome> YI_TI_MARSHES = register("yi_ti_marshes", GOTBiomePreset.MARSHES);
    public static final ResourceKey<Biome> YI_TI_TROPICAL_FOREST = register("yi_ti_tropical_forest", GOTBiomePreset.JUNGLE);
    public static final ResourceKey<Biome> YI_TI_BORDER_ZONE = register("yi_ti_border_zone", GOTBiomePreset.SOUTHERN_PLAINS);

    private GOTBiomes() {}
    private static ResourceKey<Biome> register(String id, GOTBiomePreset preset) {
        GOTBiomeMetadata metadata = GOTBiomeMetadata.defaults(id, preset);
        METADATA.put(id, metadata);
        ResourceKey<Biome> key = key(id);
        BY_ID.put(id, key);
        return key;
    }
    public static Optional<ResourceKey<Biome>> byId(String id) { return Optional.ofNullable(BY_ID.get(normalize(id))); }
    public static Optional<ResourceKey<Biome>> byName(String name) { return byId(name); }
    public static Optional<GOTBiomeMetadata> metadata(String id) { return Optional.ofNullable(METADATA.get(normalize(id))); }
    public static Collection<GOTBiomeMetadata> allMetadata() { return Collections.unmodifiableCollection(METADATA.values()); }
    public static List<GOTBiomeMetadata> byClimate(GOTClimateType climate) { return METADATA.values().stream().filter(m -> m.climate() == climate).toList(); }
    public static ResourceKey<Biome> key(String id) { return ResourceKey.create(Registries.BIOME, ResourceLocation.fromNamespaceAndPath(GOTMod.MOD_ID, normalize(id))); }
    private static String normalize(String id) { return id.toLowerCase(Locale.ROOT).replace(" ", "_").replace("-", "_"); }
}
